// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXqcrDlfWfbvU6Ak_T4QfLA4ge43VKHiE',
    appId: '1:99859064289:web:085ae9432a996880afdea0',
    messagingSenderId: '99859064289',
    projectId: 'kiyolatte',
    authDomain: 'kiyolatte.firebaseapp.com',
    databaseURL: 'https://kiyolatte-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiyolatte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT5AmkvaKnITmUEaqckzonRxS0JkUagVU',
    appId: '1:99859064289:android:a326a0a5308f6903afdea0',
    messagingSenderId: '99859064289',
    projectId: 'kiyolatte',
    databaseURL: 'https://kiyolatte-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiyolatte.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Xjt6EljsZmROW_Fhlpt5F2i9-dFEUgY',
    appId: '1:99859064289:ios:f8f4d7b60cdb7eddafdea0',
    messagingSenderId: '99859064289',
    projectId: 'kiyolatte',
    databaseURL: 'https://kiyolatte-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiyolatte.firebasestorage.app',
    androidClientId: '99859064289-k3p72erq1krdj2avm7clup0ombduqo0i.apps.googleusercontent.com',
    iosClientId: '99859064289-qrd61due6crvn822d5cpv9ilqjf5fc63.apps.googleusercontent.com',
    iosBundleId: 'com.kilattech.kilatspeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Xjt6EljsZmROW_Fhlpt5F2i9-dFEUgY',
    appId: '1:99859064289:ios:f8f4d7b60cdb7eddafdea0',
    messagingSenderId: '99859064289',
    projectId: 'kiyolatte',
    databaseURL: 'https://kiyolatte-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiyolatte.firebasestorage.app',
    androidClientId: '99859064289-k3p72erq1krdj2avm7clup0ombduqo0i.apps.googleusercontent.com',
    iosClientId: '99859064289-qrd61due6crvn822d5cpv9ilqjf5fc63.apps.googleusercontent.com',
    iosBundleId: 'com.kilattech.kilatspeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXqcrDlfWfbvU6Ak_T4QfLA4ge43VKHiE',
    appId: '1:99859064289:web:bcdbf2c3431a6ea3afdea0',
    messagingSenderId: '99859064289',
    projectId: 'kiyolatte',
    authDomain: 'kiyolatte.firebaseapp.com',
    databaseURL: 'https://kiyolatte-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiyolatte.firebasestorage.app',
  );
}
